<p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">1.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>班长生活忙死了，恋爱累死了，人要死了
        </p><p class="MsoNormal"><span style="color:#078654">不是这就谈上恋爱了？</span></p><p class="MsoNormal"><span style="color:#078654">我知道这是谁，嘿嘿</span></p><p class="MsoNormal">如<span class="GramE">匿</span><span class="Emoji"><span lang="EN-US">🌚</span></span></p><p class="MsoNormal"><span style="color:#DB7800">我不会认识你吧</span></p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">2.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>高强度敲代码真的会头<span class="GramE">秃</span>
</p><p class="MsoNormal"><span style="color:#078654">加油哇同学，虽然不知道你是谁</span></p><p class="MsoNormal"><span lang="EN-US">3.</span>还可以吧，我也是班长，但我的工作量似乎反而是最少的，每天处在压力和被压力的叠加态</p><p class="MsoNormal"><span lang="EN-US">4.10</span>月<span lang="EN-US">20</span>日，下冰雹啦</p><p class="MsoNormal"><span style="color:#078654">小董同学你好</span></p><p class="MsoNormal">是来自小汤河职业技术学的<span class="SpellE"><span lang="EN-US">dcw</span></span>同学嘛<span class="Emoji"><span lang="EN-US">😋</span></span></p><p class="MsoNormal">坏了，被开盒了<span class="Emoji"><span lang="EN-US">😋</span></span></p><p class="MsoNormal"><span lang="EN-US">5.</span>武汉今天降温了，我感冒了</p><p class="MsoNormal"><span lang="EN-US">6.</span>加入田径队了，去完成高中未完成的梦想</p><p class="MsoNormal"><span class="GramE"><span style="color:#078654">酷</span></span><span style="color:#078654">！！！！</span></p><p class="MsoNormal"><span lang="EN-US">7.</span>青岛真的好冷啊</p><p class="MsoNormal"><span style="color:#078654">我去居然还有人也在青岛？！</span></p><p class="MsoNormal"><span class="Emoji"><span lang="EN-US" style="color:#0E52D4">⬆️</span></span><span style="color:#0E52D4">我去我也想知道为什么还有人也在青岛，来认识一下呗。<span lang="EN-US">qq1347108586</span></span></p><p class="MsoNormal"><span lang="EN-US">8.</span>大<span class="GramE">一</span>感觉比<span class="SpellE"><span lang="EN-US">hsy</span></span>高三累多了<span class="Emoji"><span lang="EN-US">💦</span></span></p><p class="MsoNormal"><span style="color:#078654">我也有同感</span><span class="Emoji"><span lang="EN-US" style="color:#078654">😭</span></span></p><p class="MsoNormal"><span style="color:#078654">太对了</span></p><p class="MsoNormal"><span style="color:#C21C13">大二更忙了<span lang="EN-US">+10086</span></span></p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">3.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>这里很冷啊，想家了
        </p><p class="MsoNormal"><span style="color:#078654">北京真的好冷啊<span lang="EN-US">——</span>想念南方的冬天</span></p><p class="MsoNormal"><span lang="EN-US">10.</span>大<span class="GramE">一</span>怎么这么忙啊，想念<span class="SpellE"><span lang="EN-US">hsy</span></span>的第<span lang="EN-US">n</span>天</p><p class="MsoNormal"><span lang="EN-US">11.</span>坐标深圳，听说武汉都降温了啊，啊啊啊这里还要开空调穿短袖啊</p><p class="MsoNormal"><span style="color:#58A401">大运中心的<span lang="EN-US">20</span>一碗的热干面谁不爱呢</span></p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">4.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>怎么？南京的<span class="Emoji"><span lang="EN-US">✌️</span></span>就不是<span class="Emoji"><span lang="EN-US">✌️</span></span>了？
        </p><p class="MsoNormal"><span style="color:#58A401">有南京群吗</span><span class="Emoji"><span lang="EN-US" style="color:#58A401">😋😋</span></span><span lang="EN-US" style="color:#58A401">
</span><span style="color:#58A401">强烈建议来个南京群</span><span class="Emoji"><span lang="EN-US" style="color:#58A401">🥺🥺🥺</span></span></p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">5.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>每天在冻死和差点冻死之间徘徊，感谢<span class="SpellE"><span lang="EN-US">hsy</span></span>的超绝暖气<span class="GramE">管理让</span>我有抗寒能力（
        </p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l89 level1 lfo90">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">6.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>还在和高中同学恋爱，异地恋好苦啊
        </p><p class="MsoNormal"><span lang="EN-US">14.</span>深圳的热干面是<span class="Emoji"><span lang="EN-US">💩</span></span>山，又贵又难吃，我想要豆皮<span class="GramE">酱</span>香饼荆州锅盔襄阳牛肉面热干面<span class="GramE">面</span>窝孝感米酒<span class="Emoji"><span lang="EN-US">😢</span></span></p><p class="MsoNormal"><span lang="EN-US" style="color:#078654">14</span><span class="GramE"><span style="color:#078654">楼注意</span></span><span style="color:#078654">是公安锅盔</span><span class="Emoji"><span lang="EN-US" style="color:#078654">😡😡😡</span></span></p><p class="MsoNormal"><span style="color:#078654">（对不起我错了<span lang="EN-US">TAT</span></span></p><p class="MsoNormal"><span style="color:#58A401">所以深圳的朋友们能不能<span class="GramE">建个群啊</span></span></p><p class="MsoNormal"><span class="Emoji"><span lang="EN-US">⬆️</span></span>支持 快加我<span lang="EN-US">qq3233962945</span></p><p class="MsoNormal">深圳的<span class="GramE">群来辣</span><span lang="EN-US">743214420</span></p><p class="MsoNormal"><span lang="EN-US">15.19</span>级航空班<span class="SpellE"><span lang="EN-US">ldx</span></span>，人在航大，已大三，已下团，已上飞机，刚开始压力很大，现在感觉还行吧，还不确定自己之后到底会怎么样，只能说自己一个人坚持下去吧</p><p class="MsoNormal"><span style="color:#078654">学长加油呀！</span></p><p class="MsoNormal"><span class="GramE"><span style="color:#D1A300">饭屿白</span></span><span style="color:#D1A300">和我结婚！</span></p><p class="MsoNormal">呜呜<span class="GramE">呜马上结芬呜呜呜</span></p><p class="MsoNormal"><span lang="EN-US">16.</span>报了训练营，论文和综述完全读不下去，已经完全不想再见到<span lang="EN-US">MOF</span>了</p><p class="MsoNormal"><span lang="EN-US">17.</span>大学写<span lang="EN-US">“</span>最想做的事<span lang="EN-US">”</span>，写的<span lang="EN-US">“</span>回高中<span lang="EN-US">”TAT</span></p><p class="MsoNormal"><span lang="EN-US">18.</span>我有<span lang="EN-US">30</span>个<span lang="EN-US">QQ</span><span class="GramE">群聊置</span>顶和<span lang="EN-US">11</span>个<span class="GramE">微信群聊置</span>顶，每天都对我展开疯狂信息轰炸＼<span lang="EN-US">(;´□</span>｀<span lang="EN-US">)/<span style="mso-spacerun:yes"> 
                </span></span>昨天开始用上了日程规划的软件<span lang="EN-US"><span style="mso-spacerun:yes">  </span></span>免得忘记东西
        </p><p class="MsoNormal"><span style="color:#078654">同，现在每天早起第一件事就是确认<span lang="EN-US">QQ</span><span class="GramE">和微信的</span>置顶工作群有没有什么遗漏的消息。为什么我大二班味就这么重</span><span class="Emoji"><span lang="EN-US" style="color:#078654">🥲</span></span></p><p class="MsoNormal"><span lang="EN-US">19.</span><span class="GramE">早八之</span>难难于上青天使人听此凋朱颜</p><p class="MsoNormal"><span lang="EN-US">20.</span>闭嘴！我在上课！如果你惹怒了我，我什么也做不了，正如我所说，我在上课（<span lang="EN-US">doge</span>
</p><p class="MsoNormal"><span lang="EN-US">21.</span>北京冻的我失去所有力气和手段</p><p class="MsoNormal"><span lang="EN-US" style="color:#078654"><span style="mso-spacerun:yes"> </span></span><span style="color:#078654">北京的风真的好大，比武汉还猛</span></p><p class="MsoNormal"><span lang="EN-US">22.</span><span class="GramE">早八高</span>数，开睡</p><p class="MsoNormal"><span lang="EN-US">23.</span>坐标珠海，广东快入秋！<span class="Emoji"><span lang="EN-US">😡</span></span></p><p class="MsoNormal"><span lang="EN-US">24.</span>北京好冷啊，南方人要受不了啦！哈哈，要是两个月前的我绝对不信我<span class="GramE">现在脱单了</span><span class="Emoji"><span lang="EN-US">🤣</span></span></p><p class="MsoNormal"><span lang="EN-US" style="color:#DB7800">24</span><span style="color:#DB7800">楼谁问你了</span><span class="Emoji"><span lang="EN-US" style="color:#DB7800">😠</span></span></p><p class="MsoNormal"><span class="GramE"><span style="color:#0E52D4">脱单的</span></span><span style="color:#0E52D4">豆沙了</span></p><p class="MsoNormal"><span style="color:#078654">同北京的，十月中旬已经开始穿羽绒服了啊啊啊啊好冷</span></p><p class="MsoNormal"><span style="color:#0080A0">北京真的<span lang="EN-US">……</span>啊啊啊啊好冷。怀念武汉<span class="GramE">天气第</span><span lang="EN-US">n</span>天</span></p><p class="MsoNormal">我在北京昌平很想南方</p><p class="MsoNormal">（<span class="GramE">借楼问一下</span>昌平哪儿，我也昌平，认识一下？）</p><p class="MsoNormal">（我也昌平！）</p><p class="MsoNormal">昌平生命科学园，路灯随机刷新并请吃饭（</p><p class="MsoNormal"><span lang="EN-US">25.</span>哪个大佬给<span class="SpellE"><span lang="EN-US">hsy</span></span>做一个树洞
        </p><p class="MsoNormal"><span lang="EN-US">26.</span>表白<span lang="EN-US">6</span>班<span class="SpellE"><span lang="EN-US">yzy</span></span></p><p class="MsoNormal"><span lang="EN-US">27.</span>我真的会从照片墙偷走所有老板照片</p><p class="MsoNormal"><span lang="EN-US">28.</span>没和对象去到一个城市好痛苦！</p><p class="MsoNormal"><span lang="EN-US">29.</span>喜不喜欢我五天早八</p><p class="MsoNormal"><span lang="EN-US">30.</span>湖北的<span class="GramE">过早过早过早</span>啊啊啊啊啊啊啊啊</p><p class="MsoNormal"><span lang="EN-US">31.</span>每次假期从西安回武汉真的好贵<span class="Emoji"><span lang="EN-US">😭</span></span></p><p class="MsoNormal"><span class="GramE">西安西安</span> 现在好冷 据说秦岭山上下雪所以我们挨冻</p><p class="MsoNormal"><span lang="EN-US">32.</span>上海没有热干面<span class="Emoji"><span lang="EN-US">🙂</span></span>
</p><p class="MsoNormal"><span lang="EN-US">33.</span>人在华师，<span class="GramE">早八晚</span>十，八小时实验，但还是可以帮大家看看牢周</p><p class="MsoNormal"><span lang="EN-US">34.</span>我想回家</p><p class="MsoNormal"><span lang="EN-US">35.</span>超级怀念华师一</p><p class="MsoNormal"><span lang="EN-US">36.</span>来个人帮我做题</p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_507" o:spid="_x0000_i1208" type="#_x0000_t75" alt="WAK275Q3ABQHK"
 style='width:414.75pt;height:81.75pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image1004.jpg" o:title="WAK275Q3ABQHK"/>
</v:shape><![endif]-->
<?if !vml?><img alt="WAK275Q3ABQHK" border="0" height="109" src="汤逊湖北路1号回忆录.files/image1005.jpg" v:shapes="Picture_x0020_507" width="553"/>
<?endif?>
</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_508" o:spid="_x0000_i1207" type="#_x0000_t75" alt="A47M55Q3AAQD6"
 style='width:415.15pt;height:165pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image1006.jpg" o:title="A47M55Q3AAQD6"/>
</v:shape><![endif]-->
<?if !vml?><img alt="A47M55Q3AAQD6" border="0" height="220" src="汤逊湖北路1号回忆录.files/image1007.jpg" v:shapes="Picture_x0020_508" width="554"/>
<?endif?>
</span></p><p class="MsoNormal"><span style="color:#078654">（看看是不是这个？）</span></p><p class="MsoNormal"><span lang="EN-US">37.</span><span class="GramE">活人微死</span> 为什么文科生还要学<span lang="EN-US">Python
            </span>微积分 逻辑学和统计学<span class="Emoji"><span lang="EN-US">😀</span></span></p><p class="MsoNormal"><span style="color:#078654">点了，高等数学请离开我的世界</span><span class="Emoji"><span lang="EN-US" style="color:#078654">😅</span></span></p><p class="MsoNormal"><span style="color:#078654">点了 为什么小语种要学<span lang="EN-US">python…</span>为什么小语种要学<span lang="EN-US">python…</span>为什么小语种要学<span lang="EN-US">python…</span></span></p><p class="MsoNormal"><span lang="EN-US">38.</span>非常好大二生活，使我连轴转</p><p class="MsoNormal"><span lang="EN-US">39.</span>欢迎报考武汉唯一<span lang="EN-US">985</span>关山<span class="GramE">口男子</span>职业技术学校</p><p class="MsoNormal"><span lang="EN-US">40.</span>在学校有点孤独也没有熟人想念高中同学们！</p><p class="MsoNormal"><span lang="EN-US">41.</span>北京冷死了，且没有热干面（所有的所谓热干面都是依托不知道啥东西）</p><p class="MsoNormal"><span style="color:#078654">北京，我们学校和学校附近的热干面都是<span lang="EN-US">15</span>往上走，做的还一坨</span><span class="Emoji"><span lang="EN-US" style="color:#078654">😓</span></span></p><p class="MsoNormal"><span style="color:#0E52D4;background:#D9EEFB">难吃啊啊啊啊啊啊啊</span></p><p class="MsoNormal"><span lang="EN-US">42.</span>大学生活远不如高中的一集，感觉比高中生活累多了，再次怀念高中同学</p><p class="MsoNormal"><span lang="EN-US">43.</span>怎么还没有放寒假</p><p class="MsoNormal"><span lang="EN-US">44.</span>合肥能不能建个群</p><p class="MsoNormal"><span style="color:#DB7800">柯南附议</span></p><p class="MsoNormal"><span lang="EN-US">45.</span><span class="GramE">小马小马</span>我好想你<span class="Emoji"><span lang="EN-US">😞</span></span></p><p class="MsoNormal">奕宝我的未来不能没有你<span class="Emoji"><span lang="EN-US">😭😭😭</span></span></p><p class="MsoNormal"><span lang="EN-US">46.whu</span>的热干面不好吃<span class="Emoji"><span lang="EN-US">😠</span></span>还行吧（我感觉</p><p class="MsoNormal"><span style="color:#D1A300">真的不如<span class="SpellE"><span lang="EN-US">hsy</span></span>的热干面</span><span class="Emoji"><span lang="EN-US" style="color:#D1A300">😭</span></span></p><p class="MsoNormal"><span style="color:#D1A300">远不如<span class="SpellE"><span lang="EN-US">hsy</span></span>我哭</span>
</p><p class="MsoNormal"><span class="GramE">枫园巨</span>难吃</p><p class="MsoNormal"><span class="GramE">面妈妈</span>的还不错 但还是想<span class="SpellE"><span lang="EN-US">hsy</span></span>的<span class="Emoji"><span lang="EN-US">🥺</span></span></p><p class="MsoNormal">不会是<span class="GramE">桂园</span>的吧，，，，<span class="GramE">桂园</span>的热干面真的不敢恭维，田园的<span class="GramE">面妈妈</span>还是很好吃的</p><p class="MsoNormal"><span lang="EN-US">47.</span>还是会不时怀念<span class="Emoji"><span lang="EN-US">🥲</span></span>尽管大三了</p><p class="MsoNormal"><span lang="EN-US">48.</span>长春真的好冷，冬天来的好快，<span class="GramE">早八真的</span>好累</p><p class="MsoNormal"><span lang="EN-US">49.</span>长春好冷＋<span lang="EN-US">1</span>，楼上在哪里啊</p><p class="MsoNormal"><span lang="EN-US">50.</span>感觉大学不如高中开心</p><p class="MsoNormal"><span lang="EN-US">51.</span>好想华一，很好的学校</p><p class="MsoNormal"><span lang="EN-US">52.</span>想回去读高三<span lang="EN-US">QAQ</span></p><p class="MsoNormal"><span lang="EN-US">53.</span>别来武大，加油出<span class="GramE">武汉吧家人们</span></p><p class="MsoNormal"><span lang="EN-US">54.</span>别来华科（华中科技<span lang="EN-US">b</span><span class="GramE">站大学</span>与自习高中）！加油考出武汉，<span lang="EN-US">HUST</span>真的比华师一累多了，实在不行建议去隔壁武大。</p><p class="MsoNormal">唉，华中监控大学</p><p class="MsoNormal"><span style="color:#58A401">呜呜<span class="GramE">呜</span>后悔辣，人在电气学院很崩溃</span></p><p class="MsoNormal"><span style="color:#58A401">呜呜<span class="GramE">呜</span>后悔辣，人在<span lang="EN-US">AIA</span>很崩溃</span></p><p class="MsoNormal"><span style="color:#58A401">呜呜<span class="GramE">呜</span>后悔辣，人在医学院很崩溃</span></p><p class="MsoNormal"><span style="color:#58A401">呜呜<span class="GramE">呜</span>后悔辣，人<span class="GramE">在计院很</span>崩溃</span></p><p class="MsoNormal"><span lang="EN-US">55.</span><span class="GramE">武理早上</span>没有豆皮吃，我很恼火</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">whut</span></span><span class="GramE">越苑一</span>楼的热干面好吃</p><p class="MsoNormal"><span lang="EN-US">omg</span>我<span class="GramE">也是武理的</span>，<span class="GramE">话说武理有</span>校友群吗
        </p><p class="MsoNormal"><span lang="EN-US">56.</span>欢迎来西北工业大，<span class="GramE">被名字</span>耽误的好学校，好吃好住学习，漂亮女生特别多，<span class="GramE">功成永逸</span>，三十亿薪！我在西安等着你<span lang="EN-US">( ´ ▽ ` )</span>ﾉ</p><p class="MsoNormal"><span lang="EN-US">57.</span>我在武大很想<span class="SpellE"><span lang="EN-US">hsy</span></span></p><p class="MsoNormal"><span lang="EN-US">58.</span>真的没有人在华师<span class="GramE">一</span>附属大学吗</p><p class="MsoNormal"><span style="color:#58A401">有啊，<span class="SpellE"><span lang="EN-US">zpc</span></span>不就是吗</span></p><p class="MsoNormal"><span lang="EN-US">59.</span>北京孩子们有群吗<span class="Emoji"><span lang="EN-US">👀</span></span>
</p><p class="MsoNormal"><span lang="EN-US">60.</span>大学真的比高中还累啊，上不完的水课，开不完的会，做不完的事，学不会的数学<span class="Emoji"><span lang="EN-US">😭😭</span></span>一手抓学习一手抓学工一手抓社团一手抓恋爱一手抓家教<span class="Emoji"><span lang="EN-US">😭😭</span></span>鼠<span class="GramE">鼠窝啊</span>洗到临头了</p><p class="MsoNormal"><span lang="EN-US">70.</span>高中生活感觉更快乐吧，大学更自由！想念高中！！我不想在郊区读大学</p><p class="MsoNormal"><span lang="EN-US">71.</span>放我回高三休息两天<span lang="EN-US">——</span>要赶<span class="SpellE"><span lang="EN-US">ddl</span></span>要赶<span class="SpellE"><span lang="EN-US">kpi</span></span>真的经常相似<span lang="EN-US">——</span>如果不是和<span class="SpellE"><span lang="EN-US">npy</span></span><span class="GramE">天天聊我就</span>一头撞死了（划掉）</p><p class="MsoNormal"><span lang="EN-US">72.</span>南京的孩子真的太想念<span class="SpellE"><span lang="EN-US">hsy</span></span>了<span class="Emoji"><span lang="EN-US">😭</span></span></p><p class="MsoNormal"><span lang="EN-US">73.</span>想看各个班级的蹭饭地图呀！！！</p><p class="MsoNormal"><span lang="EN-US">74.</span>杭州菜死难吃！！</p>