<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_32" o:spid="_x0000_i1717" type="#_x0000_t75" alt="2UAEP5Q3ADAGM"
 style='width:414.75pt;height:276.75pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image052.jpg" o:title="2UAEP5Q3ADAGM"/>
</v:shape><![endif]-->
<?if !vml?><img alt="2UAEP5Q3ADAGM" height="369" src="汤逊湖北路1号回忆录.files/image053.jpg" v:shapes="Picture_x0020_32" width="553"/>
<?endif?>
</span></p><p class="MsoNormal">这一届<span class="SpellE"><span lang="EN-US">tp</span></span>奖得主又该颁给谁呢？？？</p><p class="MsoNormal">谁在操控我的电脑？？！谁在控<span lang="EN-US">zi</span>我的电脑屏幕 <span class="GramE">不</span>你们<span class="SpellE"><span lang="EN-US">si</span></span>可以的 我<span lang="EN-US">Zi</span>道你们是可以的</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">zian</span></span><span lang="EN-US"> tai <span class="SpellE">zhong</span> <span class="SpellE">si</span> <span class="SpellE">si</span> <span class="SpellE">su</span>/<span class="SpellE">zu</span>
                zi <span class="SpellE">wu</span> <span class="SpellE">tei</span> <span class="SpellE">cin</span> <span class="SpellE">si</span></span></p><p class="MsoNormal">这个世界没有你们想的那么黑暗</p><p class="MsoNormal">四啊，怎么<span class="GramE">不</span>四的，就四对的</p><p class="MsoNormal">把你的指甲收起来</p><p class="MsoNormal">致敬传奇接线板</p><p class="MsoNormal">那边那个红彤彤的似<span class="SpellE"><span lang="EN-US">senmou</span></span>啊</p><p class="MsoNormal">（为什么你们可以发语音？）</p><p class="MsoNormal">剥夺你的五四奖</p><p class="MsoNormal">唢呐 这个就四指明了写作方向</p><p class="MsoNormal">再看看～</p><p class="MsoNormal">唢呐</p><p class="MsoNormal">哦哦哦～</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">hzx</span></span>，这个题你来<span class="SpellE"><span lang="EN-US">suo</span></span></p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US" style="color:#DB7800">hzx</span></span><span lang="EN-US" style="color:#DB7800"> re</span><span style="color:#DB7800">：不来</span></p><p class="MsoNormal">涂平吗，那无敌了，哈哈</p><p class="MsoNormal">你们班还不如十二班</p><p class="MsoNormal"><span style="color:#D1A300">（十二班<span class="GramE">就是坠吊的</span></span></p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">si</span></span>二班<span class="GramE">嗦</span><span lang="EN-US">…</span></p><p class="MsoNormal">你们班</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">hzx</span></span><span lang="EN-US"> </span>你<span class="SpellE"><span lang="EN-US">suo</span></span></p><p class="MsoNormal">灵活小鞋</p><p class="MsoNormal"><span lang="EN-US">
<o:p> </o:p>
</span></p>