<p class="MsoNormal">这怎么能少了我们肥肥燕呢</p><p class="MsoNormal"><span lang="EN-US">↑</span>（南通是你吗？）狗叫，我刚来</p><p class="MsoNormal">偶尔阴阳怪气的燕燕子瑞平教室后面一黑板的科比</p><p class="MsoNormal"><span lang="EN-US" style="color:#58A401">2003</span><span style="color:#58A401">限定版，我看看照片还在不在</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_39" o:spid="_x0000_i1709" type="#_x0000_t75" alt="6J45P5Y3ACQCG"
 style='width:414.75pt;height:310.9pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image067.jpg" o:title="6J45P5Y3ACQCG"/>
</v:shape><![endif]-->
<?if !vml?><img alt="6J45P5Y3ACQCG" height="415" src="汤逊湖北路1号回忆录.files/image068.jpg" v:shapes="Picture_x0020_39" width="553"/>
<?endif?>
</span></p><p class="MsoNormal">喜欢开冷笑话，上课讲了很多很多故事</p><p class="MsoNormal">会抓壮丁给她女儿讲小学奥数</p><p class="MsoNormal">对学生真的很好，特别高三心情不好学不进去就找燕子聊天～～</p><p class="MsoNormal"><span class="GramE">日常吐槽</span><span class="SpellE"><span lang="EN-US">yxc</span></span>抓她迟到和工资低
        </p><p class="MsoNormal">泰山老母</p><p class="MsoNormal">老是找眼镜呀，办公室一副车上一副</p><p class="MsoNormal">雀巢配特<span class="GramE">仑</span>苏，到处借牛奶</p><p class="MsoNormal">高二升高三那暑假她要我们写二舅的作文，我和我同桌各写一篇长文批判这种赞美苦难的风气，<span class="GramE">喜提两个</span><span lang="EN-US">0</span>分（不过我写的没我同桌好就是</p><p class="MsoNormal"><span style="color:#58A401">楼上一看就知道是谁的程度<span lang="EN-US">↑</span><span class="GramE">哈哈哈哈</span><span class="SpellE"><span lang="EN-US">djz</span></span>吧</span></p><p class="MsoNormal">补药开<span class="GramE">我口牙</span><span class="SpellE"><span lang="EN-US">qaq</span></span></p><p class="MsoNormal">可以跟赵老师分享和讨论过自己最近喜欢的书籍（虽然每次讲日本文学都要被她批判）</p><p class="MsoNormal"><span style="color:#DB7800">她还批评<span class="GramE">我看莫言和</span>汪曾祺呢（话说楼上莫不是<span lang="EN-US">s</span>老师？</span><span lang="EN-US" style="color:#078654">(</span><span style="color:#078654">哈哈 我不是</span><span style="color:#C21C13">（所以是瑶<span class="GramE">瑶</span>吗</span><span style="color:#A639D7">不是<span class="GramE">哈哈哈哈</span>我是<span lang="EN-US">2002</span>的</span><span style="color:#078654">啊那我是谁<span lang="EN-US">(<span class="SpellE">emm</span></span>看来大家都很喜欢跟<span class="GramE">赵老师聊读过</span>的书呢</span></p><p class="MsoNormal"><span lang="EN-US">
<o:p> </o:p>
</span></p>