<p class="MsoNormal"><span lang="EN-US">1.hl</span>老师我们再也不逃避了！</p><p class="MsoNormal"><span lang="EN-US">2.hl</span>老师：做梦去吧！</p><p class="MsoNormal">～<span lang="EN-US">3.hl</span>从东来，我从西边走</p><p class="MsoNormal"><span lang="EN-US">4.hl</span>老师我再也不会不做作业啦！</p><p class="MsoNormal"><span lang="EN-US">5.</span>都好好学英语啊，英语以后都很重要的啊</p><p class="MsoNormal"><span lang="EN-US">6.yeah</span>～<span lang="EN-US">right</span>～</p><p class="MsoNormal"><span lang="EN-US">7.</span>说了中午要做那个填词的，你们班怎么人老不齐啊？</p><p class="MsoNormal"><span lang="EN-US">8.</span>该说不说，<span lang="EN-US">hl</span>老师有些<span lang="EN-US">supplement</span>作业<span lang="EN-US"> ppt</span>都很好啊，有很多内部资料啊（<span class="SpellE"><span lang="EN-US">bushi</span></span><span lang="EN-US"> </span>当然这里也夸一下英语组
            还是要谢谢<span lang="EN-US">hl</span>老师让我英语到了<span lang="EN-US">141</span>（我相信真的有很大一方面部分是<span lang="EN-US">hl</span>老师的功劳</p><p class="MsoNormal"><span lang="EN-US">9.</span>高考押题王（两个高难填词全押中了，这实力你说牛<span class="GramE">不</span>牛）</p><p class="MsoNormal"><span lang="EN-US">10.</span>命题人：贺莉<span lang="EN-US"><span style="mso-spacerun:yes"> 
                </span></span>审题人：贺莉</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">   
                </span></span>命题人：高三英语<span class="GramE">备课组</span> 审题人：贺莉</p><p class="MsoNormal"><span lang="EN-US">11.</span><span class="GramE">该陪</span><span lang="EN-US">hl</span>演出的我选择视而不见<span lang="EN-US">~(<span class="SpellE">bushi</span></span></p><p class="MsoNormal"><span lang="EN-US">12.</span>说实话，那天下午一嗓子，我心<span class="SpellE"><span lang="EN-US">pongpong</span></span><span class="GramE">跳一下午</span></p><p class="MsoNormal"><span lang="EN-US">13.got it</span>？</p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_91" o:spid="_x0000_i1656" type="#_x0000_t75" alt="MARWX5Y3ABAAE"
 style='width:101.25pt;height:103.5pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image167.jpg" o:title="MARWX5Y3ABAAE"/>
</v:shape><![endif]-->
<?if !vml?><img alt="MARWX5Y3ABAAE" border="0" height="138" src="汤逊湖北路1号回忆录.files/image167.jpg" v:shapes="Picture_x0020_91" width="135"/>
<?endif?>
</span></p><p class="MsoNormal"><span style="color:#078654">看到这张图我就想到偷偷低头看稿子的<span lang="EN-US">hl</span></span></p><p class="MsoNormal"><span lang="EN-US">14.</span>对不起贺老师身为课代表其实我一直都不写作业</p><p class="MsoNormal"><span lang="EN-US">15.</span>傲慢与偏见真的好看，快乐的挤出来的晚自习时光</p>