<p class="MsoNormal">娃儿～<span class="GramE">咋笑的</span>这么好呢</p><p class="MsoNormal"><span lang="EN-US">“</span><span class="GramE">诶</span>～你看<span class="Emoji"><span lang="EN-US">↘</span></span>这<span class="Emoji"><span lang="EN-US">↘</span></span>娃<span class="Emoji"><span lang="EN-US">↗</span></span><span lang="EN-US">er”</span></p><p class="MsoNormal">谁还记得那堆因为表观遗传花色各不相同的小猪喝奶的震撼照片</p><p class="MsoNormal">记得，因为过于震撼</p><p class="MsoNormal">想念段老师了<span class="Emoji"><span lang="EN-US">😭</span></span><span lang="EN-US">hen</span>
</p><p class="MsoNormal">（活捉社社！ （ 看到小黄同学了<span class="Emoji"><span lang="EN-US">🤭</span></span></p><p class="MsoNormal">社社别跑（</p><p class="MsoNormal"><span lang="EN-US">www</span></p><p class="MsoNormal">怀念每一个躲进办公室自习的晚上 <span lang="EN-US" style="color:#DB7800">+1+1</span><span style="color:#DB7800">狠狠<span lang="EN-US">+1</span>了<span lang="EN-US"><span style="mso-spacerun:yes">  </span></span>高三下学期隔几节课就会钻到段老师办公室里玩</span></p><p class="MsoNormal">特别好的段妈<span lang="EN-US">…</span>虽然我的生物最后考的并不好，估计以后也不会再接触有关的内容了，但是还是很想念您办公室里温暖的感觉</p><p class="MsoNormal">半永久嬉皮笑脸<span class="Emoji"><span lang="EN-US">😀</span></span></p><p class="MsoNormal">段妈是世界上最温暖的老师！</p><p class="MsoNormal">生物是高度分化的学科</p><p class="MsoNormal">大家大学不要选生物<span class="GramE">》</span><span lang="EN-US" style="color:#D1A300">“</span><span style="color:#D1A300">我喜欢你们选物理化学，等你们学到后面会发现，<span class="GramE">诶</span></span><span class="Emoji"><span lang="EN-US" style="color:
#D1A300">↗</span></span><span style="color:#D1A300">，你们最后还是会把自己学的用到生物上面，那我就开心了<span lang="EN-US">” </span></span></p><p class="MsoNormal"><span lang="EN-US" style="color:#D1A300"><span style="mso-spacerun:yes"> </span></span><span style="color:#D1A300">（好可爱的段老师<span lang="EN-US">555<span style="mso-spacerun:yes">  </span></span>她的办公室是最温暖的避风港</span></p><p class="MsoNormal">有几个娃儿写大题喜欢在最后扭一扭<span lang="EN-US">~</span></p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">slx</span></span>怎么上课又在睡觉呢～</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">yjj</span></span>！！</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">dbj</span></span>和她的小女儿</p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_144" o:spid="_x0000_i1598" type="#_x0000_t75" alt="6O52T6I3AAAEC"
 style='width:414.75pt;height:553.15pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image275.jpg" o:title="6O52T6I3AAAEC"/>
</v:shape><![endif]-->
<?if !vml?><img alt="6O52T6I3AAAEC" border="0" height="738" src="汤逊湖北路1号回忆录.files/image276.jpg" v:shapes="Picture_x0020_144" width="553"/>
<?endif?>
</span></p>