<p class="MsoNormal">问过黄老师一两次作文，感觉黄老师特别霸气特别喜欢啊</p><p class="MsoNormal">恭喜升任学校办公室主任</p><p class="MsoNormal">在教室里唱过昆曲，好听！</p><p class="MsoNormal">带我们去室外上课，真的很幸福</p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l1 level1 lfo2">
<?if !supportLists?><span lang="EN-US" style="font-family:Wingdings;mso-fareast-font-family:Wingdings;
mso-bidi-font-family:Wingdings"><span style="mso-list:Ignore">l<span style='font:7.0pt "Times New Roman"'> 
                    </span></span></span>
<?endif?>你说<span lang="EN-US">HZ</span>，不好意思，一开始看到这个名字想到的是赫兹（<span lang="EN-US">doge</span>），现在回首来看，也许记不得太多的事情，上她的课程也是零零碎碎，高一上了部分，高二上了部分，高三才稳定下来，记得有很多同学上课说她水课，怎么说呢，感觉理性来看，确实是在讲一些考试用不上的东西，思考一些奇奇怪怪的问题，做出一些完全意想不到的假设。但是，也许正是这些课堂上与考试无关的东西，让我真正意义上重新认识了语文。在遇到<span lang="EN-US">HZ</span>之前，语文在我心中的地位不是很高，一部分源于自己不好的表达，一部分源于老师对好词好句过分的追求，让我对语文这个学科产生了偏见吧，觉得它是感性的学科，而身为一个理科的没那么感性的人，完全就学不懂语文。<span lang="EN-US">HZ</span>让我知道语文是可以充满理性的，它可以是感性和理性的混合体，很多课堂上一次次的思考，让我发现其实语文这个学科包罗万象，真正可以做到包含很多其他学科，并且对问题产生深度的思考。虽然很多事情现在都记不得啦，但是我们两个人不时地讨论问题到晚自习结束的画面还历历在目，每次都得提到自己家住的很远，得<span class="GramE">开至少</span>半个小时的车，然后自己早点走是有原因的，反正当时跟生物老师<span lang="EN-US">DBJ</span>形成鲜明对比，之前笑这个<span class="GramE">事情笑</span>了好久。也是<span lang="EN-US">HZ</span>，慢慢地见证了自己的成长吧，不论是思维上不断地拓展以及批判性思维的锻炼，还是语言表达能力的提升，我觉得她不管怎么说能够当上语文组组长是当之无愧的，很厉害的宝藏老师，只要平常时间多一点就更好了（<span lang="EN-US">doge</span>）<span lang="EN-US">(</span>完<span lang="EN-US">)</span>
</p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_49" o:spid="_x0000_i1699" type="#_x0000_t75" alt="75CJL6A3ABAHS"
 style='width:415.15pt;height:311.25pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image086.jpg" o:title="75CJL6A3ABAHS"/>
</v:shape><![endif]-->
<?if !vml?><img alt="75CJL6A3ABAHS" height="415" src="汤逊湖北路1号回忆录.files/image087.jpg" v:shapes="Picture_x0020_49" width="554"/>
<?endif?>
</span></p><p class="MsoNormal">一直超级怀念晚黄老师值班的时候去找她改作<span class="GramE">文或者</span>闲聊<span lang="EN-US">……24</span>级小朋友没有黄老师教语文真的太可惜了。黄老师主打一个闲聊式教学，但是不可否认上语文课真的很有趣，就连有时候难以抵挡的睡意也会被平移到下一节课，还有经典的大连海事大学传奇志愿（）等一系列人生故事。怎么说呢，黄老师才是我心中真正语文教育者的形象，也<span class="GramE">超级有</span>气质，虽然有时候因为自己的高位也会向我们吐<span class="GramE">槽很多</span>工作上的事情（）但这不是更显得有人情味吗（恼）作文因为自己<span lang="EN-US">“</span>独特<span lang="EN-US">”</span>的风格分数也是忽高忽低，但是每次去找黄老师问作文确实收货丰富，缺点就是好多人排队啊！！！！还有就是同上，博雅湖那次<span class="GramE">课虽然</span>不记得上啥了但是课本<span class="GramE">身真的</span>印象十分深刻<span lang="EN-US">……</span></p><p class="MsoNormal">还有第一次看到上图中的高<span lang="EN-US">p</span>图的时候吐槽了好半天</p>