<p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l90 level1 lfo91">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">1.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>好想念华一之巅，好想再回去看看<span class="Emoji"><span lang="EN-US">🥺😢</span></span>
</p><p class="MsoNormal"><span style="color:#078654">想念当时和几个朋友在上面<span lang="EN-US">K</span>歌</span></p><p class="MsoNormal"><span lang="EN-US">2.</span>想念华一食堂的热干面了<span lang="EN-US">🥹🥹</span>（疫情的时候留校每天一碗<span class="Emoji"><span lang="EN-US">😭</span></span>）</p><p class="MsoNormal"><span style="color:#A639D7">这没得说，这是真好吃，吃了三年没吃厌</span></p><p class="MsoNormal"><span style="color:#58A401">这是真好吃啊</span></p><p class="MsoNormal"><span style="color:#58A401">想念<span lang="EN-US">…</span>想念<span lang="EN-US">…</span>想念<span lang="EN-US">……<span class="GramE">…………</span></span></span></p><p class="MsoNormal"><span style="color:#DB7800">是真的好好吃啊<span lang="EN-US">……</span>加鸡蛋绝了，我整整吃了半年</span></p><p class="MsoNormal"><span style="color:#58A401">一碗热干面刚好从食堂走到教学楼吃完</span></p><p class="MsoNormal">讲真没吃过比华一食堂更好处的热干面</p><p class="MsoNormal"><span style="color:#58A401">想吃是想吃，但我还是想问芝麻酱怎么能那么干的</span></p><p class="MsoNormal">好神奇，<span class="GramE">明明比</span><span class="SpellE"><span lang="EN-US">hsy</span></span>做得好的热干面有很多但还是忘不掉冬天早晨热气腾腾的热干面，，，想哭</p><p class="MsoNormal"><span style="color:#078654">华一的热干面是我吃过最好吃的，就算高三走读了也还一直念着这一口！为什么中午不卖！！！</span></p><p class="MsoNormal"><span lang="EN-US">3.</span>华一之巅的小彩灯还在不在呢？<span lang="EN-US">ˁ˙˟˙ˀ</span></p><p class="MsoNormal"><span lang="EN-US">4.</span>华师一男同为什么这么多</p><p class="MsoNormal"><span style="color:#D1A300">华师<span lang="EN-US">0</span></span></p><p class="MsoNormal">因为华师<span lang="EN-US">1</span>，所以<span lang="EN-US">0</span>溢</p><p class="MsoNormal"><span lang="EN-US">5.</span>想念每个在食堂端碗面慢慢走到教学楼的早晨</p><p class="MsoNormal"><span style="color:#078654">点了</span></p><p class="MsoNormal"><span style="color:#078654">点了</span></p><p class="MsoNormal">点了</p><p class="MsoNormal">点了，有一次上十个人还从操场绕了一圈免得被<span class="SpellE"><span lang="EN-US">yxc</span></span>抓到</p><p class="MsoNormal"><span lang="EN-US">6.</span><span class="GramE">彼杨德</span>六班什么时候团建</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">  
                </span></span><span style="color:#D1A300">同问</span></p><p class="MsoNormal"><span lang="EN-US">7.</span>好怀念学生组织和社团啊，很有凝聚力的大家庭</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">  
                </span></span><span style="color:#58A401">确实</span></p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">  
                </span></span>点了，最怀念团委</p><p class="MsoNormal" style="margin-left:21.0pt;text-indent:-21.0pt;mso-list:l90 level1 lfo91">
<?if !supportLists?><span lang="EN-US"><span style="mso-list:Ignore">2.<span style='font:7.0pt "Times New Roman"'>     
                    </span></span></span>
<?endif?>如果能回到高中我一定要<span class="GramE">疯狂扩列</span> 这么可爱的华一<span lang="EN-US">er</span>不多认识几个实在太可惜了
        </p><p class="MsoNormal"><span lang="EN-US">9.</span>好怀念站在大礼堂舞台上的时候<span class="Emoji"><span lang="EN-US">😭😭😭</span></span></p><p class="MsoNormal"><span lang="EN-US">10.</span>有人还记得光阴的故事吗（当事人下面来踢我</p><p class="MsoNormal"><span lang="EN-US" style="color:#078654"><span style="mso-spacerun:yes">      </span></span><span style="color:#078654">当事人表示为什么还有人记得</span></p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">     
                </span></span>当事人来了，高考<span class="GramE">暑假上</span>了教我们舞的老师的私教课，，老师是<span class="SpellE"><span lang="EN-US">whu</span></span>的学姐<span class="Emoji"><span lang="EN-US">🥺</span></span></p><p class="MsoNormal"><span lang="EN-US">11.</span><span class="GramE">国演</span><span class="SpellE"><span lang="EN-US">yyds</span></span><span lang="EN-US">!</span></p><p class="MsoNormal"><span lang="EN-US">12.</span>想念华师<span class="GramE">一</span>的大雪</p><p class="MsoNormal"><span lang="EN-US">13.</span>看的眼睛尿尿了。好想永远留在高中。</p><p class="MsoNormal"><span lang="EN-US">14 </span>想念<span lang="EN-US">20 21</span>级一起的<span lang="EN-US">CG</span>社！一力<span class="GramE">亩永远</span>忘不了学长学姐和同届的友<span class="GramE">友</span>，作为社长受过学长学姐和同届活跃成员们很大帮助，，非常感激大家！</p><p class="MsoNormal">（<span lang="EN-US">20</span>届左右真的是我在社团最美好的时光也是整个高中最温暖的地方，我永远喜欢大家<span class="Emoji"><span lang="EN-US">😭😭😭</span></span>）（<span class="SpellE"><span lang="EN-US">ylm</span></span>：对啊啊啊啊啊啊啊啊啊啊当时的氛围太好了大家都很活跃很有凝聚力，很幸福温暖的一段时光）</p><p class="MsoNormal"><span style="color:#C21C13">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#DA326B">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#D1A300">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#D1A300">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#D1A300">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#D1A300">永远的袭击社！</span></p><p class="MsoNormal"><span style="color:#D1A300">永远的袭击社！</span></p><p class="MsoNormal"><span lang="EN-US">15.</span>想念周鹏程，徐惠是谁，不熟真不熟</p><p class="MsoNormal"><span style="color:#58A401">小心文档安全（）</span></p><p class="MsoNormal"><span style="color:#C21C13">回避这个敏感的滑梯（）</span></p><p class="MsoNormal"><span style="color:#078654">楼上的，怕啥啊，一个处级干部能翻了天了</span><span class="Emoji"><span lang="EN-US" style="color:#078654">😆</span></span><span style="color:#078654">，毕业了还怕<span lang="EN-US">?</span></span></p><p class="MsoNormal"><span style="color:#C21C13">徐<span class="GramE">惠感觉</span>把<span class="SpellE"><span lang="EN-US">hsy</span></span>往衡水的方向在带？</span></p><p class="MsoNormal">那就反了<span lang="EN-US">TMD</span>！<span lang="EN-US"><span style="mso-spacerun:yes"> 
                </span>@ghn</span></p><p class="MsoNormal"><span style="color:#C21C13">欠缺学生铁拳了</span><span class="Emoji"><span lang="EN-US">😡</span></span></p><p class="MsoNormal"><span lang="EN-US">16.</span>哪个华一<span lang="EN-US">er</span>不是在校的时候骂学校，毕业了比谁都怀恋</p><p class="MsoNormal"><span style="color:#C21C13">不不不毕业了也骂，详情参考<span class="SpellE"><span lang="EN-US">qz</span></span>和<span class="SpellE"><span lang="EN-US">xh</span></span></span><span class="Emoji"><span lang="EN-US" style="color:#C21C13">🤣👉</span></span></p><p class="MsoNormal"><span class="Emoji"><span lang="EN-US">👆</span></span>但是我在学校也不怎么骂<span class="SpellE"><span lang="EN-US">qaq</span></span>，跟<span class="GramE">放月假周考</span>的初中同学一比较就很幸福啊（</p><p class="MsoNormal"><span lang="EN-US">17</span>啊！华师<span class="GramE">一</span>！我永远的心灵家园！真的<span class="GramE">每天每天</span>都在怀念和朋友的纯粹的活跃的美好的高中时光，是真正的<span lang="EN-US">golden time</span></p><p class="MsoNormal"><span lang="EN-US">18.</span>我果然是那种身处其中的时候<span class="GramE">浑</span>不在意甚至有点讨厌
            离开之后想想又挺怀念的贱人啊<span lang="EN-US">🥹</span></p><p class="MsoNormal"><span lang="EN-US">19.</span><span class="GramE">董远举</span><span class="SpellE"><span lang="EN-US">nmsl</span></span><span lang="EN-US"><span style="mso-spacerun:yes">  </span></span>
</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">   
                </span>↑</span>再骂就不合适了，他是好人</p><p class="MsoNormal"><span lang="EN-US">20."I can't dare to dream about <span class="SpellE">hsy</span> <span class="SpellE">any more</span>."</span></p><p class="MsoNormal"><span lang="EN-US">21.</span>补药啊，你们补药再说了，眼睛袅袅了（人在华科，想回<span class="SpellE"><span lang="EN-US">hsy</span></span>休息两天了）</p><p class="MsoNormal"><span lang="EN-US">22.</span>还在华师<span class="GramE">一</span>的时候就很喜欢，离开后更是怀念</p><p class="MsoNormal"><span lang="EN-US">23.</span><span class="GramE"><span style="color:#DA326B">敏行环路</span></span><span style="color:#DA326B">西<span class="GramE">又敏行</span>环路东，<span class="GramE">敏行环路</span>东转厚<span class="GramE">德广场</span>中
            </span></p><p class="MsoNormal"><span style="color:#DB7800">厚<span class="GramE">德广场</span>中上为何无皇宫
                <span class="GramE">敏行环路</span>东人民如潮涌</span></p><p class="MsoNormal">这个正义校长面善又友善 因此批准卷子一天考两次</p><p class="MsoNormal"><span style="color:#078654">歌名大抵是：<span class="GramE">敏行环路</span>东</span></p><p class="MsoNormal"><span class="GramE"><span style="color:#58A401">申鹤捧最</span></span><span style="color:#58A401">喜欢的一集</span></p><p class="MsoNormal">我也喜欢，哥们击<span class="GramE">个</span>掌</p><p class="MsoNormal"><span lang="EN-US">24.</span>捞捞哈尔滨的（<span class="GramE">冷爆了</span>）</p><p class="MsoNormal">们拉个群（？）</p><p class="MsoNormal"><span lang="EN-US">25.</span>好怀念高一的时候在华一之巅写下自己的<span class="GramE">梦校那个</span>意气风发的时候</p><p class="MsoNormal"><span lang="EN-US">26.</span>虽然华一之巅写下的梦想没有实现，但是能不能放我回去再写一次啊，<span class="GramE">包实现</span>的啊啊啊啊
        </p><p class="MsoNormal"><span lang="EN-US">27.</span>有很多话说，这也许就是<span lang="EN-US">“</span>却道天凉好个秋<span lang="EN-US">”</span>罢。</p><p class="MsoNormal"><span lang="EN-US">28.</span>羡慕曾经那个不知天高地厚的自己。</p><p class="MsoNormal"><span lang="EN-US">29.</span>啊啊啊怎么就回不去了</p><p class="MsoNormal"><span lang="EN-US">30.</span>博雅<span class="GramE">湖真的</span>是一个承载了很多欢欣与哀愁的地方，喜欢晚自习大课间时在那走走，透过树影看月亮</p><p class="MsoNormal"><span lang="EN-US">31.</span>尽管结果不尽人意，但我不后悔</p><p class="MsoNormal"><span lang="EN-US">32.”</span>曾许人间第一流<span lang="EN-US">“</span></p><p class="MsoNormal"><span lang="EN-US">33.</span>高考前写下<span lang="EN-US">“</span>追风赶月莫停留，平芜尽处是春山<span lang="EN-US">”</span>的坚定在混乱的大学生活中快被磨没了</p><p class="MsoNormal"><span lang="EN-US">34.</span><span class="GramE">真的真的</span>好<span class="GramE">喜欢敏行环路</span>
            喜欢华一之巅 喜欢自由自在的那些日子 希望当时陪着我一起溜出来偷偷转悠的朋友们能一直在我身边</p><p class="MsoNormal"><span lang="EN-US">35.</span>图片区真的没有那只被埋葬的猫<span class="GramE">猫</span>坟上的花嘛，更新了踢我一脚（年级群<span lang="EN-US">@</span>霁归）</p><p class="MsoNormal">？？？什么有去世的猫<span class="GramE">猫</span><span class="Emoji"><span lang="EN-US">😭</span></span>有人讲讲怎么回事吗，，，</p><p class="MsoNormal"><span class="GramE">饭屿白</span>实名怀念，有机会我一定还要再回来看看老师和<span class="GramE">宿管阿姨</span></p><p class="MsoNormal"><span lang="EN-US">36.</span>我好像找不到那个意气风发的少年了</p><p class="MsoNormal"><span lang="EN-US">37.</span>唔，那天半夜在许愿卡上写下的话，再也没有勇气告诉任何人了。那些过去没有勇气说出来的话，也再也没有机会说了</p><p class="MsoNormal"><span lang="EN-US">38.</span>春风若有<span class="GramE">怜</span>花意，可否许我再少年。</p><p class="MsoNormal"><span lang="EN-US">39.-</span>一句话证明你来过华一</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">    
                </span>-</span>水果～十元两盒～～～</p><p class="MsoNormal"><span class="GramE"><span style="color:#DB7800">水果 水果 十元量盒十元</span></span><span style="color:#DB7800">量盒</span></p><p class="MsoNormal">桌上水果～十元两盒～</p><p class="MsoNormal"><span lang="EN-US">39.</span>华一一直是我的梦中情校，一直以华一为荣。真的<span class="GramE">很爱很爱</span>这个学校，让我遇见了这么好的你们，有了这么美好的一段高中。至少可以很骄傲的说我高中是光明灿烂未来的开端</p>