<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_97" o:spid="_x0000_i1650" type="#_x0000_t75" alt="Q5OMR5Y3AAQF6"
 style='width:414.4pt;height:310.9pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image177.jpg" o:title="Q5OMR5Y3AAQF6"/>
</v:shape><![endif]-->
<?if !vml?><img alt="Q5OMR5Y3AAQF6" border="0" height="415" src="汤逊湖北路1号回忆录.files/image178.jpg" v:shapes="Picture_x0020_97" width="553"/>
<?endif?>
</span></p><p class="MsoNormal"><span lang="EN-US">1.</span>这种表单怎么能<span class="GramE">没有我志武</span>呢，真是<span lang="EN-US">so
                funny</span>啊 </p><p class="MsoNormal"><span lang="EN-US" style="mso-bidi-font-size:11.0pt">2.</span>九班小朋友速<span class="GramE">速</span>前来报道 否则我就要<span lang="EN-US">check your dictation</span>了</p><p class="MsoNormal"><span lang="EN-US">3.I will check your reciting</span></p><p class="MsoNormal"><span lang="EN-US">4.Excellent!</span></p><p class="MsoNormal"><span lang="EN-US">5.</span>脑袋这么大，却不装知识（爆了<span lang="EN-US"> #</span>欢呼<span lang="EN-US">#</span>耶<span class="GramE">耶耶</span>）</p><p class="MsoNormal"><span lang="EN-US">6.</span>古希腊掌管成语的神</p><p class="MsoNormal"><span lang="EN-US">7.</span>你们真是菜花黄疯子忙啊</p><p class="MsoNormal"><span lang="EN-US">8.Any volunteer</span>？<span lang="EN-US">No</span>？<span lang="EN-US">I'm so sorry.</span></p><p class="MsoNormal"><span lang="EN-US">9.</span></p><p class="MsoNormal"><span lang="EN-US">I can TEACH YOU</span><span class="Emoji"><span lang="EN-US">🐎🐎🐎</span></span></p><p class="MsoNormal"><span lang="EN-US">10.WHAT A PITY</span>！！！<span class="Emoji"><span lang="EN-US">😅</span></span></p><p class="MsoNormal"><span lang="EN-US">11.</span>真是信口雌黄！</p><p class="MsoNormal"><span lang="EN-US">12.</span>你们这是公牛插座吗</p><p class="MsoNormal"><span lang="EN-US">13.oi</span>，一点不知道尊老爱幼啊</p><p class="MsoNormal"><span lang="EN-US">14.</span>果然是重赏之下必有勇夫啊</p><p class="MsoNormal"><span lang="EN-US">15.</span>长腿欧巴<span lang="EN-US"><span style="mso-spacerun:yes">         
                </span></span><span class="GramE">笑拉了</span><span class="SpellE"><span lang="EN-US">hhh</span></span></p><p class="MsoNormal"><span lang="EN-US">16.</span>来自别的在<span class="SpellE"><span lang="EN-US">hsy</span></span>待了二十年的英语老师的评价：鱼植物是我们学校的老牌帅哥</p><p class="MsoNormal"><span class="GramE">捉老师</span><span class="Emoji"><span lang="EN-US">☝️</span></span>
</p><p class="MsoNormal"><span lang="EN-US">17.</span>妇女之友，每天跟女老师打排球乒乓球<span class="SpellE"><span lang="EN-US">hhh</span></span></p><p class="MsoNormal"><span lang="EN-US">18.</span>没来余志武办公室背过单词的高三是不完整的</p><p class="MsoNormal"><span lang="EN-US">19.</span>没有背过完整的<span class="SpellE"><span lang="EN-US">i</span></span><span lang="EN-US"> have a dream</span>的高三是不完整的</p><p class="MsoNormal"><span lang="EN-US">20.Are you <span class="GramE">sure?/</span>Are
                you certain?</span></p><p class="MsoNormal"><span lang="EN-US">21.very good</span></p><p class="MsoNormal"><span lang="EN-US">22.</span>余老师真的超级好！还记得高三强压下余老师幽默的课堂是我最好的良药<span lang="EN-US">……</span>记得高考<span class="GramE">考</span>数学前余老师握着我的手笑着鼓励我<span lang="EN-US">……——</span><span class="GramE">至最好</span>的志武鱼</p><p class="MsoNormal"><span lang="EN-US">23.</span>高考<span lang="EN-US">145+</span>前来感谢<span lang="EN-US">^ω^</span></p><p class="MsoNormal"><span lang="EN-US">24.</span>这么变态啊</p><p class="MsoNormal"><span lang="EN-US">25.</span>回来吧，之舞将军 </p><p class="MsoNormal"><span lang="EN-US">26.</span>现在已经是四朝元老哩，懂不懂含金量啊</p><p class="MsoNormal"><span lang="EN-US">27.general</span>前来报道，恭迎志武</p>