<p class="MsoNormal"><span class="SpellE"><span lang="EN-US">wwy</span></span>老师：哎我们的作业很多吗？＋<span lang="EN-US">1+1</span></p><p class="MsoNormal">姐就是女王，自信放光芒</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">wwy</span></span>：这套卷子<span class="GramE">很</span>基础啊</p><p class="MsoNormal"><span lang="EN-US"><span style="mso-spacerun:yes">         
                </span></span>这道题很简单啊</p><p class="MsoNormal">肉眼观察法<span class="Emoji"><span lang="EN-US">🧐</span></span></p><p class="MsoNormal">离开了<span class="SpellE"><span lang="EN-US">wwy</span></span>大学还有补充作业，每<span class="GramE">周硬控我</span><span lang="EN-US">n</span>小时，但是强度还是<span class="GramE">比不过莹姐的</span>无敌补充作业哈<span class="Emoji"><span lang="EN-US">🤓👆</span></span></p><p class="MsoNormal">去找<span class="SpellE"><span lang="EN-US">wwy</span></span>问问题正好碰见她在<span class="GramE">看爽文</span>
</p><p class="MsoNormal"><span style="color:#58A401">（插个楼，找文勇的时候他在看美女</span></p><p class="MsoNormal"><span style="color:#078654">不是<span class="GramE">哈哈哈哈哈</span>，好搞笑，有一种反差</span></p><p class="MsoNormal">感觉某种程度上极大影响了我对人生态度的一位优秀的老师</p><p class="MsoNormal">超级好的老师 教的也好 感觉覆盖了高数的很多内容</p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">wwy</span></span>真的是劳模姐，每次我们都晚自习下课了，她一般都还在办公室，而且真的会一直鼓励我们。（她经常对我们文科<span class="GramE">生给予</span>超级高的希望，而且真的相信我们可以做到，下附上王老师上课的英姿，而且王姐超级温柔哒！表白<span class="GramE">表白</span></p><p class="MsoNormal">很卷的卷到带着学生一起卷的老师哈哈<span class="GramE">哈</span>，真的<span class="GramE">很感谢很感谢</span>王老师（娃娃鱼<span class="SpellE"><span lang="EN-US">bushi</span></span>）<span class="GramE">吖</span><span lang="EN-US">~</span>高三这一年在王老师的帮助下感觉数学起来了一点也不那么排斥了哈哈<span class="GramE">哈</span><span lang="EN-US">~</span><span class="GramE">很好很好</span>的老师<span lang="EN-US">~</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_61" o:spid="_x0000_i1687" type="#_x0000_t75" alt="7TWVJ5Q3ABAC4"
 style='width:415.15pt;height:311.25pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image110.jpg" o:title="7TWVJ5Q3ABAC4"/>
</v:shape><![endif]-->
<?if !vml?><img alt="7TWVJ5Q3ABAC4" height="415" src="汤逊湖北路1号回忆录.files/image111.jpg" v:shapes="Picture_x0020_61" width="554"/>
<?endif?>
</span></p><p class="MsoNormal">凭什么把<span class="SpellE"><span lang="EN-US">wwy</span></span>和竞赛教练分开列举，人家不在竞赛班照样有学生高一进省队不更能说明实力
        </p><p class="MsoNormal">讲的真的很有体系，关键是对我们和她自己都很有自信啊！从来不<span lang="EN-US">push</span>我们，考得好<span class="GramE">就夸考得</span>不好就鼓励，每次考崩溃一听她课上总结的就会很有信心。喜欢不要<span class="GramE">我演板的</span>数学课哈哈<span class="GramE">哈</span>但好在为数不多的几次都<span class="GramE">做对</span>了（这真的<span class="GramE">很增长</span>我的自信<span class="SpellE"><span lang="EN-US">qaq</span></span></p><p class="MsoNormal">高一被<span class="SpellE"><span lang="EN-US">wwy</span></span>带 当时跟一个女生形影不离
            于是<span class="SpellE"><span lang="EN-US">wwy</span></span>再也没分清我俩<span lang="EN-US">…</span>我俩一个选的历史一个选的物理
            后来上<span class="SpellE"><span lang="EN-US">wwy</span></span>补习班没写作业<span class="SpellE"><span lang="EN-US">wwy</span></span>问我文科作业不应该很少吗为什么没时间写（我选的物理<span lang="EN-US">…</span></p><p class="MsoNormal">笑死了我对上面这段印象也超级深刻（（很有压迫感的一个问题</p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">王文<span class="GramE">莹超棒</span>的呜呜<span class="GramE">呜呜</span>。还记得每次写她的数学作业（又多又难）写到崩溃，交作业的时候她还会安慰你数学就是螺旋式上升的过程只要努力就有结果呜呜<span class="GramE">呜</span>，她点亮了我的整个高三，认真负责又有耐心。（建议所有数学老师向<span class="SpellE"><span lang="EN-US">wwy</span></span>看齐哈哈<span class="GramE">哈哈</span>）（穿衣风格非常有特点，这衣服在我身上啥样我想都不敢想哈哈<span class="GramE">哈</span>，但是她穿好好看）</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_62" o:spid="_x0000_i1686" type="#_x0000_t75" alt="PWATF5Y3AAQF6"
 style='width:415.15pt;height:433.9pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image112.jpg" o:title="PWATF5Y3AAQF6"/>
</v:shape><![endif]-->
<?if !vml?><img alt="PWATF5Y3AAQF6" height="579" src="汤逊湖北路1号回忆录.files/image113.jpg" v:shapes="Picture_x0020_62" width="554"/>
<?endif?>
</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">真的很爱<span class="SpellE"><span lang="EN-US">wwy</span></span>，虽然不学数学了，但还是会记得她</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">这是一个简单题</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">（改题型前）（导数多选压轴）大家怎么都选一个就跑呀～<span class="GramE">这保险嘛</span>，我看<span class="GramE">这题拿五分</span>就<span class="GramE">挺保险</span>的～</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">真的<span class="GramE">很好很好</span>的数学老师</span><span class="Emoji"><span lang="EN-US" style="mso-bidi-font-size:11.0pt">😭</span></span><span style="mso-bidi-font-size:11.0pt">超级温柔呜呜<span class="GramE">呜</span></span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">好美啊<span lang="EN-US">WINWIN</span>，高考时候送考我们那个考场
                抱抱我，给我很大安慰啊</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">还有就是<span lang="EN-US">WINWIN</span>真的相信你，她不觉得你不行，她觉得你好棒 。</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><!--[if gte vml 1]><v:shape
 id="Picture_x0020_63" o:spid="_x0000_i1685" type="#_x0000_t75" alt="OFSGL5Y3AAAFW"
 style='width:115.5pt;height:118.5pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="汤逊湖北路1号回忆录.files/image114.jpg" o:title="OFSGL5Y3AAAFW"/>
</v:shape><![endif]-->
<?if !vml?><img alt="OFSGL5Y3AAAFW" height="158" src="汤逊湖北路1号回忆录.files/image114.jpg" v:shapes="Picture_x0020_63" width="154"/>
<?endif?>
</span></p><p class="MsoNormal"><span lang="EN-US" style="mso-bidi-font-size:11.0pt">WINWIN</span><span style="mso-bidi-font-size:11.0pt">真的提供了很多情绪价值呜呜<span class="GramE">呜呜</span>，高三几度崩溃都是在数学课上冷静下来开始觉得自己还有希望的</span><span class="Emoji"><span lang="EN-US" style="mso-bidi-font-size:11.0pt">😭</span></span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">心中真神不解释</span></p><p class="MsoNormal"><span style="mso-bidi-font-size:11.0pt">救了俺的数学。唯一真神！人有一种独特的气质。</span></p><p class="MsoNormal"><span lang="EN-US">
<o:p> </o:p>
</span></p>