<p class="MsoNormal">永远忘不了瑾的小海报和读书报告还有小组作业</p><p class="MsoNormal">永远忘不了<span lang="EN-US">19</span>班<span class="GramE">零上交</span>的惊人战绩</p><p class="MsoNormal">背<span lang="EN-US">I have a dream </span>免了<span class="GramE">一</span><a style="mso-comment-reference:潜_3;mso-comment-date:20241022T1121">整个</a><span lang="EN-US">
<?if !supportAnnotations?><a class="msocomanchor" href="#_msocom_3" id="_anchor_3" language="JavaScript" name="_msoanchor_3" onmouseout="msoCommentHide('_com_3')" onmouseover="msoCommentShow('_anchor_3','_com_3')">
<font face="微软雅黑">[潜3]</font>
</a>
<?endif?><span style="mso-special-character:comment"> </span>
</span>国庆作业<span class="Emoji"><span lang="EN-US">🙈</span></span></p><p class="MsoNormal">最负责最温柔的英语老师<span class="SpellE"><span lang="EN-US">mua</span></span><span lang="EN-US">!(*╯3╰)</span></p><p class="MsoNormal"><span class="SpellE"><span lang="EN-US">Jeanish</span></span><span class="Emoji"><span lang="EN-US">❤️</span></span></p><p class="MsoNormal">命中注定的<span lang="EN-US">Jean</span><span class="Emoji"><span lang="EN-US">😭</span></span>
</p><p class="MsoNormal">当我在大学课堂上看到<span lang="EN-US">reading circle</span>的那一刻我终于意识到<span lang="EN-US">Jean</span>的超绝含金量
        </p><p class="MsoNormal">我是<span lang="EN-US">Jean</span>的<span class="Emoji"><span lang="EN-US">🐶</span></span>（<span class="SpellE"><span lang="EN-US">lzr</span></span>圆梦）</p><p class="MsoNormal">我爱<span class="SpellE"><span lang="EN-US">hj</span></span>，我要学英语！<span lang="EN-US"><span style="mso-spacerun:yes">  </span>—<span class="SpellE">lzr</span></span></p><p class="MsoNormal">办公室集中营（尖叫<span lang="EN-US">*</span>）</p><p class="MsoNormal"><span class="GramE">特别特别</span>好的<span lang="EN-US">jean....</span></p><p class="MsoNormal"><span lang="EN-US">This is what an awesome teacher looks like</span><span class="Emoji"><span lang="EN-US">😎</span></span></p><p class="MsoNormal"><span lang="EN-US">308</span>见（微笑）</p><p class="MsoNormal"><span lang="EN-US">308</span>，启动！（还是感谢黄老师让我这个吊车尾的考到了<span lang="EN-US">129</span>）（顺便祝福我的某个同学在这里圆梦！）</p><p class="MsoNormal">你们是按人品投的吗？你也有？<span style="color:#D1A300">呜呜我的呆呆</span><span class="Emoji"><span lang="EN-US" style="color:#D1A300">😭</span></span></p><p class="MsoNormal"><span lang="EN-US">308</span>集中改造营的营长</p><p class="MsoNormal">被架空的、干体力活的小英语课代表</p><p class="MsoNormal"><span lang="EN-US">↑</span>一眼<span class="SpellE"><span lang="EN-US">cjh</span></span>我笑死了</p><p class="MsoNormal">可是没人告诉我大学英语真的不如<span lang="EN-US">Jean</span>交的，就说作业布置那么多但是确实干货很有用<span class="Emoji"><span lang="EN-US">😭</span></span></p><p class="MsoNormal">有没有人加一张<span lang="EN-US">Jean</span>高考改卷摸鱼打水被拍的图片啊好好<span class="GramE">好</span></p><p class="MsoNormal">有没有人想想办法让<span lang="EN-US">Jean</span>来教我大英<span lang="EN-US">……</span></p><p class="MsoNormal">感谢<span lang="EN-US">Jean</span>让我的高考从<span lang="EN-US">110</span>提到了<span lang="EN-US">140</span>以上啊啊啊<span class="Emoji"><span lang="EN-US">😭</span></span></p><p class="MsoNormal">感谢瑾<span class="GramE">瑾</span>让我圆梦<span lang="EN-US">137</span>！！！</p><p class="MsoNormal"><span lang="EN-US">
<o:p> </o:p>
</span></p>