name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.28"
          enable-cache: true
      - run: uv sync --locked
      - run: uv run --locked mkdocs gh-deploy --force
